name: Jedwali
description: "A semester schedule management system for students."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  get: ^4.6.6
  toastification: ^1.2.0
  flutter_timer_countdown: ^1.0.7
  flutter_carousel_widget: ^2.2.0
  http: ^1.2.1
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
