// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgj-uFHiZ4DzqT5-si13takAFPRfGP8EI',
    appId: '1:425261138142:web:da7eac412f5e61cc0a424f',
    messagingSenderId: '425261138142',
    projectId: 'jedwali-project-jan',
    authDomain: 'jedwali-project-jan.firebaseapp.com',
    storageBucket: 'jedwali-project-jan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjI1nMVy3QlHFEkNUgVzIOjPr0DCClcts',
    appId: '1:425261138142:android:51960a04be975e100a424f',
    messagingSenderId: '425261138142',
    projectId: 'jedwali-project-jan',
    storageBucket: 'jedwali-project-jan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgur2ZDyiPRs8WHzo73x01GnLSY3j6TpA',
    appId: '1:425261138142:ios:a7ddb06b3a07f41b0a424f',
    messagingSenderId: '425261138142',
    projectId: 'jedwali-project-jan',
    storageBucket: 'jedwali-project-jan.appspot.com',
    iosBundleId: 'com.example.endSemProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgur2ZDyiPRs8WHzo73x01GnLSY3j6TpA',
    appId: '1:425261138142:ios:d3a37a959830dfe40a424f',
    messagingSenderId: '425261138142',
    projectId: 'jedwali-project-jan',
    storageBucket: 'jedwali-project-jan.appspot.com',
    iosBundleId: 'com.example.endSemProject.RunnerTests',
  );
}
